---
language: python
services: docker

env:
  global:
    - ROLE_NAME: test
  matrix:
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule==2.22rc6 docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

#notifications:
#  slack:
#    secure: XXXX
