---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ./ansible-lint-rules

install:
  - pip install --upgrade ansible==2.8.3 docker
  - pip install molecule==2.22rc6
  - pip install ansible-lint==4.1.0
  - ansible --version
  - ansible-lint --version
  - molecule --version

script:
  - yamllint . -c .yamllint
  - ansible-lint . -c .ansible-lint
  - molecule test -s default
