---
- name: Add mongodb-org repo key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "9DA31620334BD75D9DCB49F368818C72E52529D4"
    state: present
  register: mongodb_repo_key_result
  until: mongodb_repo_key_result is success
  retries: 10
  tags: mongo_install

- name: Add mongodb-org repo
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu/{{ ansible_distribution_release }}/mongodb-org/{{ mongo_version }} multiverse"
    update_cache: true
  tags: mongo_install

- name: Install mongodb-org
  apt:
    pkg: mongodb-org
    state: present
    update_cache: true
  register: mongodb_install_result
  until: mongodb_install_result is success
  retries: 10
  tags: mongo_install

- name: Enable mongod service
  service:
    name: mongod
    enabled: true
    state: started
  tags: mongo_install
