---
- name: Add mongodb-org repo key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  register: mongodb_repo_key_result
  until: mongodb_repo_key_result is success
  retries: 3
  tags: mongo_install

- name: Add mongodb-org repo
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongo_version }} multiverse"
    update_cache: true
  tags: mongo_install

- name: Install mongodb-org
  apt:
    pkg: mongodb-org
    update_cache: true
    force_apt_get: true    ## workaround to remove apt warnings
  register: mongodb_install_result
  until: mongodb_install_result is success
  retries: 3
  tags: mongo_install

- name: Enable mongodb service
  systemd:
    name: mongod
    enabled: true
    state: started
  tags: mongo_install
