---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
      - python3
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
  create_sequence:
    - create
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
