---
- name: Converge
  hosts: all
  become: yes
  vars:
    mongo_bind_ip: 0.0.0.0

  pre_tasks:
    - name: Install requirement packages
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - dirmngr
        - net-tools

  roles:
    - role: test
