---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install python3.6 for Ansible
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal python3-zipstream)
      changed_when: false

    - name: Install requirement packages
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: true
        force_apt_get: true    ## workaround to remove apt warnings
      loop:
        - dirmngr
        - net-tools
        - curl
        - apt-transport-https
        - software-properties-common
