---
- name: Verify MongoDB
  hosts: all
  tasks:
  - name: Check file exists
    stat:
      path: "/etc/hosts"
    register: hosts_file

  - name: Assert file status
    assert:
      that:
        - "hosts_file.stat.exists"
      quiet: false
      success_msg: "hosts file test PASSED"
      fail_msg: "hosts file test FAILED"

  - name: Check BindIP
    lineinfile:
      path: /etc/mongod.conf
      regexp: "^  bindIp:"
      line: "  bindIp: 0.0.0.0"
    register: "mongodb_conf"

  - name: Assert Bind IP status
    assert:
      that:
        - "not mongodb_conf.changed"
      success_msg: "Bind IP test PASSED"
      fail_msg: "Bind IP test FAILED"
      quiet: false

  - name: Check service status
    systemd:
      name: mongod
      state: started
    check_mode: true
    register: mongodb_service

  - name: Assert service status
    assert:
      that:
        - "mongodb_service.status.SubState == 'running'"
      success_msg: "mongodb service test PASSED"
      fail_msg: "mongodb service test FAILED"
      quiet: false

  - name: Check port status
    wait_for:
      host: 0.0.0.0
      port: 27017
      state: started
      timeout: 3
